In [ ]:
#Problem 1
import numpy as np

# Task 1: Initialize an empty array with size 2X2
empty_array = np.empty((2, 2))
print("Empty Array (2x2):")
print(empty_array)

# Task 2: Initialize an all-one array with size 4X2
ones_array = np.ones((4, 2))
print("\nAll-One Array (4x2):")
print(ones_array)

# Task 3: Return a new array of given shape and type, filled with fill value
fill_value_array = np.full((3, 3), 7)
print("\nArray filled with value 7 (3x3):")
print(fill_value_array)

# Task 4: Return a new array of zeros with same shape and type as a given array
given_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros Array with same shape as given array:")
print(zeros_like_array)

# Task 5: Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("\nOnes Array with same shape as given array:")
print(ones_like_array)

# Task 6: Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
converted_array = np.array(new_list)
print("\nConverted Numpy Array from list:")
print(converted_array)



Empty Array (2x2):
[[4.64011796e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]

All-One Array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with value 7 (3x3):
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Array with same shape as given array:
[[0 0 0]
 [0 0 0]]

Ones Array with same shape as given array:
[[1 1 1]
 [1 1 1]]

Converted Numpy Array from list:
[1 2 3 4]


In [ ]:
#Problem 2
import numpy as np

# Task 1: Create an array with values ranging from 10 to 49
array_10_to_49 = np.arange(10, 50)
print("Array with values ranging from 10 to 49:")
print(array_10_to_49)

# Task 2: Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values ranging from 0 to 8:")
print(matrix_3x3)

# Task 3: Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:")
print(identity_matrix)

# Task 4: Create a random array of size 30 and find the mean of the array
random_array = np.random.random(30)
array_mean = random_array.mean()
print("\nRandom Array of size 30:")
print(random_array)
print("Mean of the array:", array_mean)

# Task 5: Create a 10x10 array with random values and find the min and max
random_matrix = np.random.random((10, 10))
matrix_min = random_matrix.min()
matrix_max = random_matrix.max()
print("\n10x10 Random Matrix:")
print(random_matrix)
print("Minimum value:", matrix_min)
print("Maximum value:", matrix_max)

# Task 6: Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero Array with 5th element replaced with 1:")
print(zero_array)

# Task 7: Reverse an array arr = [1, 2, 0, 0, 4, 0]
arr = [1, 2, 0, 0, 4, 0]
reversed_array = arr[::-1]
print("\nReversed Array:")
print(reversed_array)

# Task 8: Create a 2D array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on border and 0 inside:")
print(border_array)

# Task 9: Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Odd rows: Start at 0, step 2
checkerboard[::2, 1::2] = 1  # Even rows: Start at 1, step 2
print("\n8x8 Checkerboard Pattern Matrix:")
print(checkerboard)



Array with values ranging from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values ranging from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array of size 30:
[0.20404905 0.12984502 0.01089005 0.15509586 0.02298843 0.79605467
 0.91616448 0.08490832 0.90517843 0.56756866 0.10748956 0.83726754
 0.61864725 0.43875603 0.00250845 0.26540456 0.57605338 0.12750447
 0.65548709 0.99175647 0.46202166 0.10655987 0.92620147 0.51245283
 0.8320453  0.93333783 0.50619523 0.58492704 0.64222117 0.09448068]
Mean of the array: 0.4671353608371214

10x10 Random Matrix:
[[0.71206873 0.58871982 0.78476431 0.4312398  0.42965536 0.71872064
  0.41364205 0.7755131  0.24223916 0.31116214]
 [0.37259489 0.72275646 0.68474665 0.57908811 0.09276564 0.85034979
  0.57340528 0.32946613 0.4545258  0.12972482]
 [0.9420727  0.74054518 0.21490856 0.57518207 0.6578

In [ ]:
#Problem 3
import numpy as np

# Initialize the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Task 1: Add the two arrays
array_sum = x + y
print("Addition of x and y:")
print(array_sum)

# Task 2: Subtract the two arrays
array_diff = x - y
print("\nSubtraction of x and y:")
print(array_diff)

# Task 3: Multiply the array x with an integer (e.g., 3)
array_mult = x * 3
print("\nMultiplication of x with 3:")
print(array_mult)

# Task 4: Find the square of each element of the array x
array_square = np.square(x)
print("\nSquare of each element in x:")
print(array_square)

# Task 5: Find the dot product
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\nDot product of v and w:", dot_vw)
print("Dot product of x and v:")
print(dot_xv)
print("Dot product of x and y:")
print(dot_xy)

# Task 6: Concatenate x and y along rows and v and w along columns
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.vstack((v, w))  # Alternatively: np.column_stack((v, w))
print("\nConcatenate x and y along rows:")
print(concat_xy_row)
print("Concatenate v and w along columns:")
print(concat_vw_col)

# Task 7: Concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\nConcatenate x and v:")
    print(concat_xv)
except ValueError as e:
    print("\nConcatenation of x and v failed. Error message:")
    print(e)
    print("Reason: The dimensions of x (2x2) and v (1D array) are incompatible for concatenation along rows or columns.")



Addition of x and y:
[[ 6  8]
 [10 13]]

Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

Multiplication of x with 3:
[[ 3  6]
 [ 9 15]]

Square of each element in x:
[[ 1  4]
 [ 9 25]]

Dot product of v and w: 219
Dot product of x and v:
[29 77]
Dot product of x and y:
[[19 22]
 [50 58]]

Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
[[ 9 10]
 [11 12]]

Concatenation of x and v failed. Error message:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: The dimensions of x (2x2) and v (1D array) are incompatible for concatenation along rows or columns.


In [ ]:
#Problem 4
import numpy as np

# Given matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A_inv = I (Inverse of A)
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("1. A * A_inv = \n", I)

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB = \n", AB)
print("   BA = \n", BA)

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)
B_T = np.transpose(B)
A_T = np.transpose(A)
B_T_A_T = np.dot(B_T, A_T)
print("\n3. (AB)^T = \n", AB_T)
print("   B^T * A^T = \n", B_T_A_T)


# 4. Solve the system of linear equations using the Inverse Method
# The system: 2x - 3y + z = -1, x - y + 2z = -3, 3x + y - z = 9
A_system = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_system = np.array([-1, -3, 9])

# Calculate the inverse of A and solve for X
A_inv_system = np.linalg.inv(A_system)
X_solution = np.dot(A_inv_system, B_system)
print("\n4. Solution (x, y, z) = ", X_solution)




1. A * A_inv = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. AB = 
 [[23 13]
 [51 29]]
   BA = 
 [[36 44]
 [13 16]]

3. (AB)^T = 
 [[23 51]
 [13 29]]
   B^T * A^T = 
 [[23 51]
 [13 29]]

4. Solution (x, y, z) =  [ 2.  1. -2.]
